export const loremIpsum =`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac porttitor ipsum, vel luctus velit. Duis vel turpis sollicitudin, dictum orci vitae, ullamcorper sem. Aliquam hendrerit accumsan tempor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean at accumsan odio. Fusce fermentum est sed tortor consectetur, ut vehicula tortor tristique. Cras iaculis sed arcu quis lacinia. Fusce venenatis dapibus aliquet.

Nulla arcu leo, lobortis vel mauris non, congue placerat metus. Phasellus aliquam arcu magna, vitae faucibus libero mollis id. Aenean pretium augue quis dolor fringilla, sed tempor neque euismod. Etiam vulputate volutpat magna, ut sodales velit tristique vel. Suspendisse potenti. Sed vitae auctor ante. Sed mollis, nisi ac ultricies luctus, urna nisi pharetra ipsum, ut varius est mi id eros. Etiam dapibus mauris ut aliquet condimentum. Vestibulum vitae lectus vel neque viverra mollis id vel mi.

Nulla facilisi. Mauris vehicula sit amet felis eget tincidunt. Nam euismod et nisi vel finibus. Suspendisse congue eget augue id mattis. Cras molestie dignissim metus, quis pulvinar sapien vestibulum at. Fusce ante neque, feugiat sed pulvinar sit amet, pharetra eget metus. In in dolor non nibh interdum hendrerit at vehicula neque. Mauris pulvinar tellus ut eleifend rutrum. Praesent non iaculis neque. Duis at convallis magna. Suspendisse sit amet lacus nibh.

Nullam sapien velit, pharetra id est sed, tempus pharetra elit. Proin sagittis purus nec auctor convallis. Phasellus dapibus diam vitae leo tincidunt sollicitudin. Suspendisse quis neque eu nibh semper auctor id id sem. Integer consequat porta lectus vel dapibus. Mauris ut pharetra orci, non aliquet purus. Duis vel nibh diam. Pellentesque at metus vitae dolor placerat pellentesque. Nam ultricies imperdiet mi, vel vehicula sem tempus finibus. Duis gravida mauris vitae mollis molestie. Maecenas eleifend efficitur magna in dignissim. Nulla ac ultricies ex.

Fusce fermentum velit ac ligula sagittis scelerisque. Mauris imperdiet est massa, ullamcorper congue turpis tincidunt ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur quis enim nec dui facilisis porta. Praesent maximus tortor non ex feugiat dictum. Suspendisse potenti. Donec sed pretium diam, vel porttitor nunc. Nunc quis lacus sit amet lorem porttitor egestas vel vel velit. Nam dapibus ante id mi dapibus congue a vel justo. Curabitur augue urna, pellentesque interdum semper sed, commodo et sem. Aliquam eget odio volutpat metus tincidunt mattis. Nam vulputate augue nec tempor lobortis. Ut mollis sagittis elit, ac ultricies lacus scelerisque vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit.`;

export const paraLorem= `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac porttitor ipsum, vel luctus velit. Duis vel turpis sollicitudin, dictum orci vitae, ullamcorper sem. Aliquam hendrerit accumsan tempor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean at accumsan odio. Fusce fermentum est sed tortor consectetur, ut vehicula tortor tristique. Cras iaculis sed arcu quis lacinia. Fusce venenatis dapibus aliquet.`;

export const lineLorem= `Lorem Ipsum Dolor Sit Amet`;

